### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by merlinuwe** [calomancer/obsidian.nomedia#1]
Thanks for your great plugin.

You say, "This plugin runs on start up and every second after that.". Is it better to let it run only once (and again, when there are new folders)?

(Would't it be better to call it after a new folder is made?)

**Comment by calomancer** [comment]
I need to update the description. It's does only run on start up and when a folder or file is created.

**Comment by merlinuwe** [comment]
Thank you very much for clarification, so I can alway let it on:

![image](https://github.com/calomancer/android.nomedia/assets/4138869/119a70b4-a634-4882-813b-565e7c9705a9)

**Comment by calomancer** [comment]
Yes, you can leave it on. I've updated the Readme.
